### PR TITLE
Allow directory filter for listing

### PR DESCRIPTION
**Pull request by appukuttan-shailesh**
Implements directory level filtering for both `Container` and `PublicContainer`

**Example 1.1:** Using `Container`
```
from hbp_archive import Container
c = Container("sp6_validation_data", CSCS_PASSWORD)
files = c.list(dir_path="synapseunit")
files
```
Output:
> ['synapseunit/observations_bidirectional.json',
 'synapseunit/observations_ltd.json',
 'synapseunit/observations_ltp.json']

**Example 1.2:** Using `Container` and sub-folder level
```
files = c.list(dir_path="cerebellum/purkinje")
files
```
Output:
> ['cerebellum/purkinje/spontaneous_firing_rate.json']

**Example 2.1:** Using `PublicContainer`
```
from hbp_archive import Container, PublicContainer
pc = PublicContainer("https://object.cscs.ch/v1/AUTH_c0a333ecf7c045809321ce9d9ecdfdea/hippocampus_optimization")
files = pc.list(dir_path="mouse/CA1/v1.0.0/CA1_pyr_cACpyr_type2_d141027_0201_03_20190524162055")
files
```
Output:
> ['mouse/CA1/v1.0.0/CA1_pyr_cACpyr_type2_d141027_0201_03_20190524162055/CA1_pyr_cACpyr_type2_d141027_0201_03_20190524162055.zip',
 'mouse/CA1/v1.0.0/CA1_pyr_cACpyr_type2_d141027_0201_03_20190524162055/CA1_pyr_cACpyr_type2_d141027_0201_03_20190524162055_meta.json',
 'mouse/CA1/v1.0.0/CA1_pyr_cACpyr_type2_d141027_0201_03_20190524162055/CA1_pyr_cACpyr_type2_d141027_0201_03_20190524162055_responses.png',
 'mouse/CA1/v1.0.0/CA1_pyr_cACpyr_type2_d141027_0201_03_20190524162055/d141027_0201_03_morph.jpeg']

**Example 2.1:** Using `PublicContainer` and extension
```
files = pc.list(dir_path="mouse/CA1/v1.0.0/CA1_pyr_cACpyr_type2_d141027_0201_03_20190524162055", extension=".json")
files
```
Output:
> ['mouse/CA1/v1.0.0/CA1_pyr_cACpyr_type2_d141027_0201_03_20190524162055/CA1_pyr_cACpyr_type2_d141027_0201_03_20190524162055_meta.json']

### CODE REVIEW

**Comment by appukuttan-shailesh** [comment]
@lbologna: Can you take a look if the above features suffice? Let me know if any other feature would be useful.

Note that the method `list()` offers a few other filters as well. See:
https://github.com/HumanBrainProject/hbp_archive/blob/master/hbp_archive.py#L407

**Review by apdavison — APPROVED** [review]
Looks fine to me.

**Comment by lbologna** [comment]
> @lbologna: Can you take a look if the above features suffice? Let me know if any other feature would be useful.
> 
> Note that the method `list()` offers a few other filters as well. See:
> https://github.com/HumanBrainProject/hbp_archive/blob/master/hbp_archive.py#L407
> 
> (I will update the [docs](https://hbp-archive.readthedocs.io/) along with this merge)

Hello @appukuttan-shailesh,
it's fine for me as well.
Thank you!

**Comment by appukuttan-shailesh** [comment]
version 0.9.1 has been released on PyPI

**Pull request merged**
